# This is a basic workflow to help you get started with Actions
name: Update H5N1 in mammals US
on:
  schedule:
    - cron: '11 1 * * *'
  workflow_dispatch:
  
jobs:
  update_film_list:
    name: Refresh CSV data daily
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: |
          python us-mammal.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add plot.png
          git commit -m "Updated index on `date` with GitHub Actions" || echo "No Changes to Commit"
          git push origin main || echo "No Changes to Commit"
